### ISSUE TITLE
`mod+enter` is already a shortcut in logseq for switching task states

### ISSUE THREAD

**Issue by lef-est** [freder/logseq-plugin-extra-editing-commands#1]
i can customize the shortcut but perhaps you want a different default :)

**Comment by freder** [comment]
I'm aware. vscode uses that shortcut; that's why I picked it.

In [v1.1.3](https://github.com/freder/logseq-plugin-extra-editing-commands/releases/tag/v1.1.3) I simply removed all default key bindings.
