### ISSUE TITLE
Empty form field for shortcut shows error

### ISSUE THREAD

**Issue by flegfleg** [freder/logseq-plugin-extra-editing-commands#2]
Leaving a Keyboard shortcut form field blank produces this error: 

`:plugin.logseq-plugin-insert-above/$shortcut$ Cannot read properties of undefined (reading 'forEach') `

**Comment by freder** [comment]
thanks for reporting – should be fixed in [v1.1.3](https://github.com/freder/logseq-plugin-extra-editing-commands/releases/tag/v1.1.3)
